[versions]
assertj = "4.0.0-M1"
fabric = "2.5.+"
hypernate = "0.1.0"
jackson = "2.20.1"
junit = "5.12.1"
junit-platform = "6.1.0-M1"
lombok-plugin = "9.1.0"
mockito = "5.20.0"
shadow = "9.3.0"
slf4j = "2.0.17"
spotless = "8.1.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
fabric-chaincode-shim = { module = "org.hyperledger.fabric-chaincode-java:fabric-chaincode-shim", version.ref = "fabric" }
hypernate = { module = "eu.bp99:hypernate", version.ref = "hypernate" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }